% HW3 - load data, run trajectory transformations and plot the resulting
% trajectories. 
%
% The data generated by this file will be modified by the autograder. 
% Your code will be tested on different trajectories captured
% by the same "camera". At the very least your code should work with
% trajectories of different length. 
%
% Remarks to consider:
%   * Arrays in Matlab can be dynamically allocated and resized
%   * Read the help files for "size" and "length" to determine if you need
%     to use them.
%   * The function "zeros" creates arrays that contain zeros

clear % clear workspace

% load the data (the file contains the arrays "rel_rob1_pos" and
% "rel_rob2_pos"
load('HW3_data.mat') 

% Run your code
[gl_rob1_pos, gl_rob2_pos] = HW3GetRobotTrajectories(rel_rob1_pos, rel_rob2_pos);

% Plot the results for visualization.
% Does it match the graphs in the homework instructions?
figure
plot(gl_rob1_pos(:,1),gl_rob1_pos(:,2),gl_rob2_pos(:,1),gl_rob2_pos(:,2))
% plot one vehicle pose every 50 frames to speed-up plotting
plot_vehicle_poses(gl_rob1_pos(1:50:end,:))
